"""Method capability metadata used by API and validation."""

SUBJECTS = {
    "self_life": "本命格局",
    "annual_luck": "流年/阶段运",
    "career": "事业工作",
    "relationship": "关系感情",
    "wealth": "财运",
    "decision": "具体决策",
    "lost_item": "寻人寻物",
    "home_fengshui": "住宅风水",
    "tarot_guidance": "塔罗指引",
    "lenormand_guidance": "雷诺曼指引",
}

METHOD_META = {
    "bazi": {
        "school": "east", "name_zh": "八字四柱", "name_en": "Four Pillars",
        "group": "命", "needs": ["birth"], "engine": "lunar-python",
        "subjects": ["self_life", "annual_luck", "career", "relationship"],
        "modes": ["natal", "annual_luck", "day_selection_context"], "default_mode": "natal",
        "required_inputs": {"natal": ["birth"], "annual_luck": ["birth"], "day_selection_context": ["birth"]},
        "recommended_for": ["长期命局", "大运流年", "性格与人生阶段"],
    },
    "bazi_v2": {
        "school": "east", "name_zh": "八字四柱·精算版", "name_en": "Four Pillars Pro",
        "group": "命", "needs": ["birth"], "engine": "lunar-python+shensha+pattern",
        "subjects": ["self_life", "annual_luck", "career", "relationship", "wealth"],
        "modes": ["natal", "annual_luck", "day_selection_context"], "default_mode": "natal",
        "required_inputs": {"natal": ["birth"], "annual_luck": ["birth"], "day_selection_context": ["birth"]},
        "recommended_for": ["深度命局分析", "用神格局", "神煞精断", "大运流年详解", "职业适配"],
    },
    "ziwei": {
        "school": "east", "name_zh": "紫微斗数", "name_en": "Zi Wei Dou Shu",
        "group": "命", "needs": ["birth"], "engine": "py-iztro",
        "subjects": ["self_life", "annual_luck", "relationship"],
        "modes": ["natal", "decadal", "annual"], "default_mode": "natal",
        "required_inputs": {"natal": ["birth"], "decadal": ["birth"], "annual": ["birth"]},
        "recommended_for": ["十二宫结构", "命身宫", "限运与关系主题"],
    },
    "qimen": {
        "school": "east", "name_zh": "奇门遁甲", "name_en": "Qi Men Dun Jia",
        "group": "卜", "needs": ["birth", "question"], "engine": "lunar-python+self",
        "subjects": ["decision", "career", "wealth", "lost_item"],
        "modes": ["hour_qimen", "day_qimen", "minute_qimen"], "default_mode": "hour_qimen",
        "required_inputs": {"hour_qimen": ["birth", "question"]},
        "recommended_for": ["短期事件", "出行求财", "行动时机"],
    },
    "liuyao": {
        "school": "east", "name_zh": "六爻", "name_en": "Liu Yao",
        "group": "卜", "needs": ["question"], "engine": "self+iching",
        "subjects": ["decision", "relationship", "career", "wealth", "lost_item"],
        "modes": ["manual_coin", "number_qigua", "time_qigua"], "default_mode": "time_qigua",
        "required_inputs": {"manual_coin": ["tosses"], "number_qigua": ["seed"], "time_qigua": ["birth"]},
        "recommended_for": ["一事一问", "成败去留", "关系与求财"],
    },
    "meihua": {
        "school": "east", "name_zh": "梅花易数", "name_en": "Plum Blossom",
        "group": "卜", "needs": ["question"], "engine": "self+time",
        "subjects": ["decision", "relationship", "career", "lost_item"],
        "modes": ["time_qigua", "number_qigua", "external_omen"], "default_mode": "time_qigua",
        "required_inputs": {"time_qigua": ["birth"], "number_qigua": ["seed"], "external_omen": ["question"]},
        "recommended_for": ["快速起卦", "外应取象", "趋势判断"],
    },
    "chenggu": {
        "school": "east", "name_zh": "称骨", "name_en": "Bone Weight",
        "group": "命", "needs": ["birth"], "engine": "self+traditional-table",
        "subjects": ["self_life"], "modes": ["traditional_weight"], "default_mode": "traditional_weight",
        "required_inputs": {"traditional_weight": ["birth"]}, "recommended_for": ["传统命重量表", "命格参考"],
    },
    "bazhai": {
        "school": "east", "name_zh": "八宅", "name_en": "Ba Zhai",
        "group": "风水", "needs": ["birth", "sitting"], "engine": "self+minggua",
        "subjects": ["home_fengshui"], "modes": ["life_gua", "residential_bazhai"], "default_mode": "life_gua",
        "required_inputs": {"life_gua": ["birth"], "residential_bazhai": ["birth", "sitting"]},
        "recommended_for": ["宅主命卦", "四吉四凶方", "门床灶方位"],
    },
    "xuankong": {
        "school": "east", "name_zh": "玄空飞星", "name_en": "Xuan Kong Fei Xing",
        "group": "风水", "needs": ["period", "sitting"], "engine": "self+luoshu",
        "subjects": ["home_fengshui"], "modes": ["residential_xuankong"], "default_mode": "residential_xuankong",
        "required_inputs": {"residential_xuankong": ["sitting"]}, "recommended_for": ["三元九运", "坐山向星", "住宅理气"],
    },
    "western": {
        "school": "west", "name_zh": "西方占星", "name_en": "Western Astrology",
        "group": "西方", "needs": ["birth"], "engine": "skyfield+self",
        "subjects": ["self_life", "relationship", "career"], "modes": ["natal"], "default_mode": "natal",
        "required_inputs": {"natal": ["birth"]}, "recommended_for": ["本命盘", "心理主题", "关系倾向"],
    },
    "vedic": {
        "school": "west", "name_zh": "吠陀占星", "name_en": "Vedic / Jyotish",
        "group": "西方", "needs": ["birth"], "engine": "skyfield+lahiri",
        "subjects": ["self_life", "annual_luck"], "modes": ["natal"], "default_mode": "natal",
        "required_inputs": {"natal": ["birth"]}, "recommended_for": ["恒星黄道", "吠陀命盘"],
    },
    "tarot": {
        "school": "west", "name_zh": "塔罗", "name_en": "Tarot",
        "group": "西方", "needs": ["question", "spread"], "engine": "random+spread-schema",
        "subjects": ["tarot_guidance", "relationship", "career", "decision"],
        "modes": ["tarot_spread"], "default_mode": "tarot_spread",
        "required_inputs": {"tarot_spread": ["question", "spread"]}, "recommended_for": ["当下议题", "关系/事业牌阵", "二择一"],
    },
    "numerology": {
        "school": "west", "name_zh": "数字命理", "name_en": "Numerology",
        "group": "西方", "needs": ["birth"], "engine": "self+pythagoras",
        "subjects": ["self_life"], "modes": ["life_path"], "default_mode": "life_path",
        "required_inputs": {"life_path": ["birth"]}, "recommended_for": ["生命灵数", "人生方向参考"],
    },
    "fengshui": {
        "school": "east", "name_zh": "风水", "name_en": "Feng Shui Composite",
        "group": "风水", "needs": ["birth", "space"], "engine": "self+bazhai+xuankong",
        "subjects": ["home_fengshui", "self_life", "decision"],
        "modes": ["fengshui_composite"], "default_mode": "fengshui_composite",
        "required_inputs": {"fengshui_composite": ["birth", "space"]},
        "recommended_for": ["综合风水评估", "八宅+玄空合参", "住宅吉凶综合判断"],
    },
    "lenormand": {
        "school": "west", "name_zh": "雷诺曼", "name_en": "Lenormand",
        "group": "西方", "needs": ["question", "spread"], "engine": "random+lenormand-36",
        "subjects": ["lenormand_guidance", "relationship", "career", "decision", "self_life"],
        "modes": ["lenormand_spread"], "default_mode": "lenormand_spread",
        "required_inputs": {"lenormand_spread": ["question"]}, "recommended_for": ["日常具体占卜", "组合解读", "Grand Tableau 全貌"],
    },
    "liuren": {
        "school": "east", "name_zh": "大六壬", "name_en": "Da Liu Ren",
        "group": "卜", "needs": ["birth"], "engine": "self+liuren-board",
        "subjects": ["decision", "career", "wealth", "relationship", "self_life"],
        "modes": ["liuren_divination"], "default_mode": "liuren_divination",
        "required_inputs": {"liuren_divination": ["birth"]}, "recommended_for": ["人事决疑", "天时地利", "三式之首"],
    },
    "tieban": {
        "school": "east", "name_zh": "铁板神数", "name_en": "Tie Ban Shen Shu",
        "group": "命", "needs": ["birth"], "engine": "self+tieban-encoding",
        "subjects": ["self_life"],
        "modes": ["tieban_base"], "default_mode": "tieban_base",
        "required_inputs": {"tieban_base": ["birth"]}, "recommended_for": ["铁板条文", "六亲校验", "神数定数"],
    },
    "cross_validator": {
        "school": "east", "name_zh": "多系统交叉验证", "name_en": "Cross-System Validator",
        "group": "验证", "needs": ["charts"], "engine": "self+ensemble",
        "subjects": ["self_life", "career", "wealth", "relationship", "health"],
        "modes": ["ensemble"], "default_mode": "ensemble",
        "required_inputs": {"ensemble": ["charts"]},
        "recommended_for": ["多术数合参", "置信度评估", "交叉验证", "系统间一致性检验"],
    },
    "hour_calibrator": {
        "school": "east", "name_zh": "时辰校准", "name_en": "Hour Calibrator",
        "group": "工具", "needs": ["birth", "traits"], "engine": "self+brute-force",
        "subjects": ["self_life"],
        "modes": ["calibrate"], "default_mode": "calibrate",
        "required_inputs": {"calibrate": ["birth"]},
        "recommended_for": ["出生时辰未知/不确定", "定盘校验", "排盘幻觉消除"],
    },
    "compatibility": {
        "school": "east", "name_zh": "八字合婚", "name_en": "Bazi Compatibility",
        "group": "合", "needs": ["two_births"], "engine": "self+bazi-compare",
        "subjects": ["relationship"],
        "modes": ["compatibility"], "default_mode": "compatibility",
        "required_inputs": {"compatibility": ["chart1", "chart2"]},
        "recommended_for": ["婚配合盘", "关系匹配度", "五行互补分析"],
    },
    "synastry": {
        "school": "west", "name_zh": "西方合盘", "name_en": "Western Synastry",
        "group": "合", "needs": ["two_births"], "engine": "skyfield+synastry+composite",
        "subjects": ["relationship"],
        "modes": ["synastry"], "default_mode": "synastry",
        "required_inputs": {"synastry": ["chart1", "chart2"]},
        "recommended_for": ["西方占星合盘", "跨盘相位分析", "宫位叠加", "组合中点盘"],
    },
}


def method_meta(method: str) -> dict:
    return METHOD_META[method]
